version: '3.7'

services:
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - type: bind
        source: ./blackbox/blackbox.yml
        target: /blackbox.yml

    command:
      - '--config.file=blackbox.yml'
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node
    ports:
      - "9100:9100"
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

