version: '3'

volumes:
  grafana_data:

services:
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox
    volumes:
      - type: bind
        source: ./blackbox/blackbox.yml
        target: /blackbox.yml
      
    command:
      - '--config.file=blackbox.yml'
    restart: always
  
  node_exporter:
    image: prom/node-exporter
    container_name: node
    restart: always
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      #- type: bind
        # source: ./prometheus/prometheus.yml
        # target: /prometheus.yml
        # read_only: true
      - ./prometheus/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - blackbox_exporter
      - node_exporter
  grafana:
    image: grafana/grafana:5.1.0
    # build: ./grafana
    user: "472:472"
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

